[package]
name = "android-ext4"
version = "0.1.0"
edition = "2024"

[dependencies]
android-sparse = "0.6.0"
bitflags = "2.10.0"
clap = {version = "4.5.53", features = ["derive"] }
nom = "7.1"
nom-derive = "0.10.1"
thiserror = "1.0"
